const API_BASE_URL = "http://localhost:3000/api";
const modelContainer = document.getElementsByClassName("modelContainer")[0];
const modelDropdown = document.querySelector(".modelDropdown1");
const searchInput = document.querySelector(".searchInput");
const searchInput1 = document.querySelector(".searchInput1");
const modelInfo = document.querySelector(".modelInfo");

async function handleChat(message, model, chatId = null) {
  try {
    const response = await fetch(`${API_BASE_URL}/chat`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        message: message,
        model: model,
        chatId: chatId,
      }),
    });

    if (!response.ok) {
      throw new Error(`HTTP error! status: ${response.status}`);
    }

    const data = await response.json();
    return data;
  } catch (error) {
    console.error("Error calling handleChat API:", error);
    throw error;
  }
}

function getModel(){
  let model;
  try {
    for (let i = 0; i < modelContainer.children.length; i++) {
      if (modelContainer.children[i].children[0].checked) {
        model = (i==0)? 'gpt-5-nano' : (i==1)? 'command-a-03-2025' : (i==2)? 'gemini-2.5-flash' :  'gpt-5-nano';
        break;
      }
    }
  } catch (error) {
    let i = modelDropdown.selectedIndex;
    model = (i==0)? 'gpt-5-nano' : (i==1)? 'command-a-03-2025' : (i==2)? 'gemini-2.5-flash' :  'gpt-5-nano';
  }
  return model;
}

async function startChat(){
  var model = getModel();
  var cur_message = searchInput.value;
  a = await handleChat(cur_message+" :\n\nFormat the entire response as a HTML text to be placed inside an answerArea div in my document, no css is requrired i have already done that also no margin padding required.", model);
  var result = a.response;
  sessionStorage.setItem('c_chat',JSON.stringify({cur_message: cur_message, model: model, response: result}));
  window.location.href = "/screen2";

}

async function reStartChat(){
  var model = getModel();
  var message = searchInput1.value;
  var chatData = sessionStorage.getItem('c_chat');
  b = JSON.parse(chatData);
  var messageOld = b.message;
  if(!messageOld){
    messageOld = b.cur_message;
  }
  var modelOld = b.model;
  var responseOld = b.response;
  var toAsk = "User asked: "+messageOld+modelOld+" Answered: "+responseOld+"Now tell: "+message+" :\n\nFormat the entire response as a HTML text to be placed inside an answerArea div in my document, no css is requrired i have already done that also no margin padding required."
  a = await handleChat(toAsk, model);
  var result = a.response;
  sessionStorage.setItem('c_chat',JSON.stringify({cur_message: message, message: toAsk, model: model, response: result}));
  document.location.reload();
}
try {
  searchInput.addEventListener("keydown", function(event) {
    if (event.key === "Enter") {
      startChat();
    }
  });  
} 
catch (error) {
  searchInput1.addEventListener("keydown", function(event) {
    if (event.key === "Enter") {
      reStartChat();
    }
  });  
}

document.addEventListener("DOMContentLoaded", function() {
  if (window.location.pathname === "/screen2") {
    var chatData = sessionStorage.getItem('c_chat');
    if (chatData) {
      var { cur_message, model, response } = JSON.parse(chatData);
        document.getElementById("userPrompt").innerText = cur_message;
        text = (model.includes('gpt')) ? 'GPT-5 Nano' : (model.includes('command')) ? 'Cohere' : (model.includes('gemini')) ? 'Gemini 2.5 Flash' : 'GPT-5 Nano';
        modelInfo.innerText = `Answer generated by ${text}`;
        response = response.replaceAll('```html\n', '');
        document.getElementById("answerArea").innerHTML = response;
        i = (model.includes('gpt'))? 0 : (model.includes('command')) ? 1 : (model.includes('gemini')) ? 2 : 3;
        modelDropdown.selectedIndex = i;

     }
  }
});

function redirect(){
  window.location.pathname = '/';
}